# Generated by Django 5.2.6 on 2025-09-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="username",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
