# Generated by Django 5.2.6 on 2025-09-20 06:31

import apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("player", "0002_alter_player_username"),
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.core.utils.generate_room_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "max_players",
                    models.IntegerField(
                        choices=[(5, "5 Players"), (6, "6 Players"), (7, "7 Players")]
                    ),
                ),
                (
                    "num_questions",
                    models.IntegerField(
                        choices=[
                            (5, "5 Questions"),
                            (6, "6 Questions"),
                            (7, "7 Questions"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Mentor starts/stops the game"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentored_room",
                        to="player.player",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(related_name="players", to="player.player"),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        help_text="Randomly selected questions for this room",
                        related_name="rooms",
                        to="question.question",
                    ),
                ),
            ],
        ),
    ]
